#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jdk-leveldb
Version  : 0.7
Release  : 2
URL      : https://github.com/dain/leveldb/archive/0.7.tar.gz
Source0  : https://github.com/dain/leveldb/archive/0.7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: jdk-leveldb-data
BuildRequires : apache-maven
BuildRequires : apache-maven2
BuildRequires : javapackages-tools
BuildRequires : jdk-aether
BuildRequires : jdk-aopalliance
BuildRequires : jdk-apache-parent
BuildRequires : jdk-atinject
BuildRequires : jdk-bsh
BuildRequires : jdk-cdi-api
BuildRequires : jdk-commons-cli
BuildRequires : jdk-commons-codec
BuildRequires : jdk-commons-collections
BuildRequires : jdk-commons-compress
BuildRequires : jdk-commons-io
BuildRequires : jdk-commons-lang
BuildRequires : jdk-commons-lang3
BuildRequires : jdk-commons-logging
BuildRequires : jdk-commons-parent
BuildRequires : jdk-doxia
BuildRequires : jdk-doxia-integration-tools
BuildRequires : jdk-doxia-sitetools
BuildRequires : jdk-enforcer
BuildRequires : jdk-glassfish-servlet-api
BuildRequires : jdk-guava
BuildRequires : jdk-guice
BuildRequires : jdk-httpcomponents-client
BuildRequires : jdk-httpcomponents-core
BuildRequires : jdk-jsoup
BuildRequires : jdk-jsr-305
BuildRequires : jdk-log4j
BuildRequires : jdk-maven-archiver
BuildRequires : jdk-maven-common-artifact-filters
BuildRequires : jdk-maven-compiler-plugin
BuildRequires : jdk-maven-dependency-tree
BuildRequires : jdk-maven-filtering
BuildRequires : jdk-maven-invoker
BuildRequires : jdk-maven-jar-plugin
BuildRequires : jdk-maven-javadoc-plugin
BuildRequires : jdk-maven-plugin-testing
BuildRequires : jdk-maven-plugin-tools
BuildRequires : jdk-maven-reporting-api
BuildRequires : jdk-maven-reporting-exec
BuildRequires : jdk-maven-resources-plugin
BuildRequires : jdk-maven-shared-incremental
BuildRequires : jdk-maven-shared-utils
BuildRequires : jdk-maven-site-plugin
BuildRequires : jdk-objectweb-asm
BuildRequires : jdk-parboiled
BuildRequires : jdk-pegdown
BuildRequires : jdk-plexus-archiver
BuildRequires : jdk-plexus-build-api
BuildRequires : jdk-plexus-cipher
BuildRequires : jdk-plexus-classworlds
BuildRequires : jdk-plexus-compiler
BuildRequires : jdk-plexus-containers
BuildRequires : jdk-plexus-i18n
BuildRequires : jdk-plexus-interactivity
BuildRequires : jdk-plexus-interpolation
BuildRequires : jdk-plexus-io
BuildRequires : jdk-plexus-sec-dispatcher
BuildRequires : jdk-plexus-utils
BuildRequires : jdk-plexus-velocity
BuildRequires : jdk-sisu
BuildRequires : jdk-slf4j
BuildRequires : jdk-snappy
BuildRequires : jdk-snappy-java
BuildRequires : jdk-surefire
BuildRequires : jdk-velocity
BuildRequires : jdk-wagon
BuildRequires : jdk-xbean
BuildRequires : jdk-xmlunit
BuildRequires : jdk-xz
BuildRequires : lxml
BuildRequires : openjdk-dev
BuildRequires : python3
BuildRequires : six
BuildRequires : xmvn
Patch1: leveldb-java-xerial-snappy.patch

%description
# LevelDB in Java
This is a rewrite (port) of [LevelDB](http://code.google.com/p/leveldb/) in
Java.  This goal is to have a feature complete implementation that is within
10% of the performance of the C++ original and produces byte-for-byte exact
copies of the C++ code.

%package data
Summary: data components for the jdk-leveldb package.
Group: Data

%description data
data components for the jdk-leveldb package.


%prep
%setup -q -n leveldb-0.7
%patch1 -p1

python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  :findbugs-maven-plugin
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  :proguard-maven-plugin leveldb
python3 /usr/share/java-utils/pom_editor.py pom_remove_dep com.google.code.findbugs:jsr305 leveldb
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  :maven-source-plugin
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  :maven-shade-plugin leveldb
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  :maven-javadoc-plugin
python3 /usr/share/java-utils/pom_editor.py pom_remove_dep org.fusesource.leveldbjni:leveldbjni-all leveldb
rm -r leveldb/src/test/java/org/iq80/leveldb/impl/NativeInteropTest.java

%build
python3 /usr/share/java-utils/mvn_build.py -f

%install
xmvn-install  -R .xmvn-reactor -n leveldb-java -d %{buildroot}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/leveldb-java/leveldb-api.jar
/usr/share/java/leveldb-java/leveldb-benchmark.jar
/usr/share/java/leveldb-java/leveldb.jar
/usr/share/maven-metadata/leveldb-java.xml
/usr/share/maven-poms/leveldb-java/leveldb-api.pom
/usr/share/maven-poms/leveldb-java/leveldb-benchmark.pom
/usr/share/maven-poms/leveldb-java/leveldb-project.pom
/usr/share/maven-poms/leveldb-java/leveldb.pom
